# Generated by Django 6.0 on 2025-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_entry_time_ticket_exit_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_metro_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
