# Generated by Django 6.0 on 2025-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='distance_from_hub',
            field=models.FloatField(default=0.0, help_text='Distance in km from the central station'),
        ),
    ]
