# Generated by Django 6.0 on 2025-12-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_station_distance_from_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='line',
            field=models.CharField(default='Red', max_length=50),
        ),
    ]
