# Generated by Django 6.0 on 2025-12-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_station_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='line',
        ),
    ]
