# Generated by Django 6.0 on 2025-12-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_station_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='route_info',
            field=models.CharField(default='Direct Trip', max_length=255),
        ),
    ]
