# Generated by Django 6.0 on 2025-12-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_route_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='route_info',
            field=models.TextField(default='Direct Trip'),
        ),
    ]
