# Generated by Django 6.0 on 2025-12-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ticket_route_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationonline',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='stationonline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metroline',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex code, e.g., #FF0000', max_length=7),
        ),
        migrations.AddField(
            model_name='stationonline',
            name='is_interchange',
            field=models.BooleanField(default=False, help_text='Check if users can change lines here'),
        ),
        migrations.AddField(
            model_name='stationonline',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of station (1, 2, 3...)'),
        ),
        migrations.RemoveField(
            model_name='stationonline',
            name='station_index',
        ),
    ]
