# Generated by Django 6.0 on 2025-12-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_stationonline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationonline',
            options={'ordering': ['id']},
        ),
    ]
